fix(Divider): adding test cases for all props
Frontify/fondue pull request #1085
Opened 2022-12-02 13:50 UTC by dominiquemb

2022-12-02 14:32 UTC, fabriciomendonca requested changes

2022-12-02 14:32 UTC, fabriciomendonca commented on src/components/Divider/Divider.cy.tsx
> +    });
This case is duplicated, right?

2022-12-05 09:25 UTC, dominiquemb commented on src/components/Divider/Divider.cy.tsx
> +    });
Yup, fixed

2022-12-05 09:27 UTC, fabriciomendonca approved these changes

2022-12-05 09:43 UTC, merged