feat(motion): define motion as peer dependency
Frontify/fondue pull request #1332
Opened 2023-03-22 13:38 UTC by rawi96

this allows us to use framer in clarify.

2023-03-22 14:22 UTC, imoutaharik approved these changes

2023-03-22 14:41 UTC, SamuelAlev commented on package.json
> +        "framer-motion": "6.4.3",
```suggestion
        "framer-motion": "^6.0.0",
```

2023-03-22 14:41 UTC, SamuelAlev requested changes

2023-03-22 14:41 UTC, SamuelAlev commented on package.json
> +        "framer-motion": "6.4.3",
```suggestion
        "framer-motion": "^6.0.0",
```

2023-03-27 07:33 UTC, SamuelAlev approved these changes

2023-03-27 07:36 UTC, merged