feat(Toast): add border style
Frontify/fondue pull request #1642
Opened 2023-11-02 11:05 UTC by fulopdaniel

2023-11-02 11:57 UTC, SamCreasey approved these changes

2023-11-02 13:37 UTC, ryancarville commented on src/components/Toast/types.tsx
> +}
Since this is specific to `Toast` maybe we should use a `map` `Record` like we do for the background?  Then implement is directly in the component?

2023-11-02 13:39 UTC, ryancarville commented on src/components/Toast/types.tsx
> +}
```suggestion
}

export const toastBorderStylesMap: Record<BorderStyle, string> = {
    [BorderStyle.Default]: 'tw-shadow-inner-line-x-strong',
    [BorderStyle.Mighty]: 'tw-shadow-inner-mighty',
};
```

2023-11-07 14:08 UTC, imoutaharik requested changes
Thanks, just one commit away to ship this :)

2023-11-07 14:08 UTC, imoutaharik commented on src/components/Toast/types.tsx
> +    variant?: ToastVariant;
Thanks a lot! @fulopdaniel 😄 
It looks good to me, the only request I'm going to make before we merge this as I just aligned with designers...is renaming the property "variant" to "theme". We plan to use `variant` in other components for something different. 😉

2023-11-08 08:38 UTC, imoutaharik approved these changes
Thanks a lot!

2023-11-08 08:46 UTC, merged