fix: update prop name "style" to "variant"
Frontify/fondue pull request #1964
Opened 2024-07-22 13:12 UTC by jose-costa-frontify

Clickup task: [86954cqzc](https://app.clickup.com/t/86954cqzc)

2024-07-23 11:25 UTC, SamuelAlev requested changes

2024-07-23 11:25 UTC, SamuelAlev commented on packages/components/src/components/Button/Button.tsx
> +                    iconStyles({ style: variant, ...props }),
You can also rename the "style" key inside to "variant"

2024-07-23 11:25 UTC, SamuelAlev commented on packages/components/src/components/Divider/Divider.tsx
> +                    style: variant,
same

2024-07-23 11:25 UTC, SamuelAlev commented on packages/components/src/components/LoadingBar/LoadingBar.tsx
> +                className={loadingBarContainerStyles({ rounded, size, style: variant })}
same

2024-07-23 11:25 UTC, SamuelAlev commented on packages/components/src/components/LoadingBar/LoadingBar.tsx
> +                    className={loadingBarStyles({ style: variant, indeterminateState: value === null })}
same

2024-07-29 12:07 UTC, jose-costa-frontify commented on packages/components/src/components/LoadingBar/LoadingBar.tsx
> +                    className={loadingBarStyles({ style: variant, indeterminateState: value === null })}
will do

2024-07-30 07:40 UTC, SamuelAlev commented on packages/components/src/components/Divider/Divider.tsx
> +                    style: variant,
```suggestion
                   variant,
```

2024-07-30 07:58 UTC, jose-costa-frontify commented on packages/components/src/components/Divider/Divider.tsx
> +                    style: variant,
thank you, done!

2024-07-30 08:31 UTC, SamuelAlev commented on packages/components/src/components/Divider/Divider.tsx
> +    variant?: DividerStyle;
Sorry I just saw it now with CTRL F 😬 
Could you update the type name to `DividerVariant` (same in other files) and also the JSDoc (same in other files)

2024-07-30 08:32 UTC, SamuelAlev approved these changes
Left a comment, after it is fixed, feel free to merge

2024-07-30 08:47 UTC, merged